// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCrawlStats() {
  return window['go']['main']['App']['GetCrawlStats']();
}

export function GetDbStatus() {
  return window['go']['main']['App']['GetDbStatus']();
}

export function StartCrawling(arg1) {
  return window['go']['main']['App']['StartCrawling'](arg1);
}

export function StopCrawling() {
  return window['go']['main']['App']['StopCrawling']();
}
