// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function GetCrawlStats():Promise<api.CrawlStats>;

export function GetDbStatus():Promise<string>;

export function StartCrawling(arg1:string):Promise<string>;

export function StopCrawling():Promise<string>;
